spring:
  datasource:
    url: jdbc:tc:postgresql:16:///vault_db
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: WARN
    dev.webisbrian.vault: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.flywaydb: WARN
    org.testcontainers: WARN