spring:
  application:
    name: vault-api
  jpa:
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  servlet:
    context-path: /api/v1